name: Dev Build

on:
  push:
    branches:
      - dev
    paths:
      - 'hardware/**'
      - '.kibot/**'
      - '.github/workflows/dev-build.yml'

permissions:
  contents: write
  actions: write

jobs:
  dev-build:
    uses: carr-james/eurorack-workflows/.github/workflows/kicad-build.yml@main
    with:
      project-name: 'CEM 3340 VCO'
      build-type: 'dev'
      boards: |
        [
           {
            "name": "control-board",
            "kibot_config": ".kibot/jlcpcb.kibot.yaml",
            "pcb_path": "hardware/control-board/control-board.kicad_pcb",
            "sch_path": "hardware/control-board/control-board.kicad_sch"
          },
          {
            "name": "main-board",
            "kibot_config": ".kibot/jlcpcb.kibot.yaml",
            "pcb_path": "hardware/main-board/main-board.kicad_pcb",
            "sch_path": "hardware/main-board/main-board.kicad_sch"
          }
        ]
      skip-checks: 'erc,drc'
      include-assembly-files: false